### ISSUE TITLE
Please add columns for:

### ISSUE THREAD

**Issue by Irinashl** [pedro-mendonca/Translation-Stats#534]
1. **Active installations** - shows the popularity of the plugin.
2. **Languages** - shows the popularity and ease of translation of the plugin.
3. **Last updated** - shows the relevance of the plugin.
Thank you.

**Comment by pedro-mendonca** [comment]
Hi, thinking about your request, here are my thoughts about it:
1. Active installs are important when you choose a plugin to install. After its installed, from the translations point of view, I don't see it adds much. Also it would require an extra API ping :)
2. How would you grade the popularity and ease of translation of the plugin?
3. Like Active installs, that is data you verify when installing. Or do you mean Last update of the translations?

**Comment by Irinashl** [comment]
I consider the "Translation Stats" plugin as an **additional tool for a translator**.

1. Active installations - if the number is very small, it means the plugin is not very popular or was released recently. And you can still wait with the translation of this plugin. And there are a lot of untranslated plugins in WP.
2. Firstly, if there are many languages, then the plugin is popular or easy to translate. Secondly, the plugin is easier to translate if there are many languages and you can pick up a hint from your neighbor.
3. If the last update was several years ago, then the plugin is not being maintained.

**Comment by pedro-mendonca** [comment]
> I consider the "Translation Stats" plugin as an additional tool for a translator.

Me also, that's why I've made it.

1. Still, while one might use a single install to keep track and manage all the translations, the main idea is to help to keep track of the translations of a specific install. For a more broad aproach of a 'all translations' I think the translate.w.org has enough tools to keep track of it, specially the plugin tables where you can sort by number of installs, etc.
Doesn't make sense to use a WP install to keep track of the translations of all the plugins :)
That being said, every data is being cached in transients, 24h by default, so this would also be applied to any more data we get.

2. I understand, but that seems to fall out of the scope of this plugin, as you probably can already get all that data comparing plugins in the translate.w.org tables. Also, if you install the plugin and want to keep track of the translations is already because you want to translate it, so it doesn't seem such a valuable data, considering the additional work needed for it :)

3. Again, a plugin code age doesn't mean much, once you've decided to install it and use it. If someone installed it, already considering that is old or new enough, it's because it is to use in the current WP install, so, it's to translate. If a plugin is being used in an install, I don't see how it's last updated date is important for being translated or not.

**Comment by Irinashl** [comment]
Ok

**Comment by pedro-mendonca** [comment]
The last updated date for the actual translation might be interesting to have in the admin colored notice shown on on debug mode.

**Comment by Irinashl** [comment]
For what?

**Comment by pedro-mendonca** [comment]
To see that the translation is somehow active, despite you're contributing or not to it.

**Comment by Irinashl** [comment]
I'm sorry, I did not get it
There are translations that do not have 90%, but they work?

**Comment by pedro-mendonca** [comment]
No, the language pack only work for >90%.
What I meant is that might be useful to see if a plugin translation was last updated last week or 9 years ago.

**Comment by Irinashl** [comment]
I don’t know, as a translator I don’t need this. 
After all, they’ve already transferred, it’s like water or money has already floated away...

**Comment by Irinashl** [comment]
But if you still consider adding columns, see above.
And it will turn out to be **All in One Translation Stats**
